[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Vincent Foley <vfoley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

[[bin]]
name = "day01"
path = "src/day01.rs"
